project_id = "jqyvtovddyqjvawnoysl"

[functions.mongodb-proxy]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

