import { useSEO } from "@/hooks/useSEO";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Monitor, Brain, TrendingUp, Star, ArrowRight } from "lucide-react";
import { SiteLayout } from "@/components/SiteLayout";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const fadeUp = { initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 } };

const valueProps = [
  { icon: Monitor, title: "Remote patient monitoring that actually works", body: "Your patients are already using health apps. The problem is those apps don't give you access. With Agatsa One, patients can share their entire health timeline with you — all readings, AI analysis, trend charts — with a single tap. Review before an appointment, not during it." },
  { icon: Brain, title: "AI pre-analysis so you see the signal, not the noise", body: "Nera AI processes every patient reading before you see it. By the time a reading lands in your provider portal, it's already been classified — normal, borderline, abnormal, or critical. You focus on what matters. Nera handles the volume." },
  { icon: TrendingUp, title: "A new revenue stream for your practice", body: "Enrol your patients in supervised Care Programmes. Set monitoring protocols. Conduct video consultations. Bill for remote monitoring management. Agatsa One's provider platform creates a new, recurring revenue stream for forward-thinking clinics — no infrastructure investment required." },
];

const steps = [
  { n: "1", title: "Register your clinic", copy: "Register your clinic on the Agatsa One Provider Portal — takes 10 minutes, free to join. Verification is completed within 24 hours." },
  { n: "2", title: "Invite your patients", copy: "Invite your patients to download Agatsa One and connect their devices. They approve sharing with your practice. You're connected instantly." },
  { n: "3", title: "Access your dashboard", copy: "Access your provider dashboard — patient list, reading summaries, alerts, AI analysis. Flag patients for follow-up. Review ECGs before appointments." },
  { n: "4", title: "Get paid for the value you deliver", copy: "Bill for remote monitoring management. Offer premium care programme oversight. Build the practice of the future — while your patients get better care between every visit." },
];

const faqs = [
  { q: "Is patient data shared with me automatically?", a: "No. Patients must explicitly approve sharing with your practice. They can also revoke access at any time. We take data privacy seriously — patients are always in control of who sees their health data." },
  { q: "Do I need to prescribe specific Agatsa One devices to my patients?", a: "No — though we do recommend specific devices based on condition. Patients can use any compatible Agatsa One device, and all readings appear in your provider portal regardless of which device they use." },
  { q: "Is the ECG data medico-legally valid?", a: "SanketLife ECG is a CDSCO Class B certified medical device. Its readings carry the same legal standing as any other certified medical device. The ECG PDF generated by Agatsa One includes timestamps, device ID, CDSCO certification number, and Nera AI analysis notes." },
  { q: "Can I enrol my patients in Care Programmes?", a: "Yes. As a provider, you can recommend specific Care Programmes for your patients. For premium oversight (where you receive weekly programme reports), this is available on our Provider Growth and Pro plans." },
];

const plans = [
  { name: "Free", price: "₹0", desc: "Individual doctors" },
  { name: "Clinic", price: "₹4,999/mo", desc: "Growing practices" },
  { name: "Hospital", price: "₹39,999/mo", desc: "Hospital-grade" },
];

export default function ForDoctorsPage() {
  useSEO({ title: "Remote Patient Monitoring for Doctors — Agatsa One Provider Platform", description: "Monitor your patients between appointments. Review ECGs, glucose trends, and BP data in your provider portal. Free to join. Start in 10 minutes." });

  return (
    <SiteLayout>
      <section className="pt-28 pb-16 bg-gradient-to-b from-background to-[hsl(260,100%,97%)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12 items-center">
          <motion.div {...fadeUp}>
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">For Doctors & Clinics</p>
            <h1 className="text-3xl md:text-5xl font-extrabold text-foreground leading-tight">
              See your patients between appointments.
              <br className="hidden md:block" /> Finally.
            </h1>
            <p className="text-lg text-muted-foreground mt-4 max-w-[520px]">
              Your patient's ECG from last Thursday. Their glucose trend over the past 30 days. Their BP at 2 AM. Their sleep quality the night before they came to you complaining of fatigue. Agatsa One gives you the data you've always wanted but never had — without adding a single minute to your workflow.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 mt-8">
              <Button className="rounded-full px-8 py-4 text-base">Book a Demo</Button>
              <Button variant="outline" className="rounded-full px-8 py-4 text-base border-2 border-primary text-primary">Download Provider Guide</Button>
            </div>
          </motion.div>
          <motion.img {...fadeUp} transition={{ duration: 0.6, delay: 0.15 }} src="https://placehold.co/580x420/1A1A2E/7C4DFF?text=Provider+Portal" alt="Agatsa One Provider Portal" className="w-full rounded-3xl shadow-2xl" />
        </div>
      </section>

      <section className="py-20 bg-background">
        <div className="max-w-5xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Why Agatsa One</p>
            <h2 className="text-3xl font-bold text-foreground">What changes when your patients use Agatsa One</h2>
          </motion.div>
          <div className="grid md:grid-cols-3 gap-6">
            {valueProps.map((v, i) => (
              <motion.div key={v.title} {...fadeUp} transition={{ duration: 0.5, delay: i * 0.1 }} className="bg-card border border-border rounded-2xl p-6">
                <v.icon className="h-8 w-8 text-primary mb-4" />
                <h3 className="text-base font-bold text-foreground">{v.title}</h3>
                <p className="text-sm text-muted-foreground mt-2">{v.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-[hsl(260,100%,97%)]">
        <div className="max-w-5xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Getting Started</p>
            <h2 className="text-3xl font-bold text-foreground">From sign-up to active monitoring in one day.</h2>
          </motion.div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((s, i) => (
              <motion.div key={s.n} {...fadeUp} transition={{ duration: 0.5, delay: i * 0.1 }} className="text-center lg:text-left">
                <div className="w-10 h-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-lg font-bold mx-auto lg:mx-0">{s.n}</div>
                <h3 className="text-lg font-bold text-foreground mt-4">{s.title}</h3>
                <p className="text-sm text-muted-foreground mt-2">{s.copy}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-background">
        <motion.div {...fadeUp} className="max-w-[800px] mx-auto px-4">
          <div className="bg-[hsl(260,100%,97%)] rounded-3xl p-8 md:p-12">
            <div className="flex gap-0.5 mb-4">
              {[...Array(5)].map((_, i) => <Star key={i} className="h-5 w-5 fill-yellow-400 text-yellow-400" />)}
            </div>
            <blockquote className="text-lg md:text-xl italic text-foreground leading-relaxed">
              "I started recommending Agatsa One to my high-risk cardiac patients 8 months ago. Today, I have 47 patients actively monitoring with the app. I check the portal dashboard every morning — takes 5 minutes. I've caught three significant arrhythmias between scheduled appointments. One of those patients would likely have ended up in the ICU. This platform has genuinely changed how I practice."
            </blockquote>
            <div className="flex items-center gap-3 mt-6">
              <img src="https://placehold.co/64x64/7C4DFF/FFFFFF?text=AK" alt="Dr. Arun Krishnamurthy" className="w-12 h-12 rounded-full" />
              <div>
                <p className="font-bold text-foreground">Dr. Arun Krishnamurthy</p>
                <p className="text-sm text-muted-foreground">Cardiologist, Apollo Hospitals, Bengaluru</p>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      <section className="py-20 bg-[hsl(260,100%,97%)]">
        <div className="max-w-4xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-10">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Pricing</p>
            <h2 className="text-3xl font-bold text-foreground">Free for doctors to join. Revenue-positive from day one.</h2>
            <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">
              The provider portal is free for individual doctors. There is no subscription fee, no setup cost, and no per-patient licensing fee for basic remote monitoring. You only pay when you scale.
            </p>
          </motion.div>
          <div className="grid md:grid-cols-3 gap-6">
            {plans.map((p, i) => (
              <motion.div key={p.name} {...fadeUp} transition={{ duration: 0.5, delay: i * 0.1 }} className="bg-card border border-border rounded-2xl p-6 text-center">
                <h3 className="text-lg font-bold text-foreground">{p.name}</h3>
                <p className="text-3xl font-extrabold text-primary mt-2">{p.price}</p>
                <p className="text-sm text-muted-foreground mt-1">{p.desc}</p>
              </motion.div>
            ))}
          </div>
          <div className="text-center mt-6">
            <Link to="/pricing" className="text-sm font-semibold text-primary hover:underline inline-flex items-center gap-1">
              View full pricing <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </section>

      <section className="py-20 bg-background">
        <div className="max-w-3xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-8">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">FAQ</p>
            <h2 className="text-2xl font-bold text-foreground">Common questions from doctors</h2>
          </motion.div>
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((f, i) => (
              <AccordionItem key={i} value={`faq-${i}`}>
                <AccordionTrigger className="text-left text-foreground">{f.q}</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{f.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      <section className="bg-primary py-20">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-primary-foreground">Ready to monitor your patients beyond the waiting room?</h2>
          <p className="text-primary-foreground/80 mt-3 text-lg">Join 500+ doctors and clinics already using Agatsa One to deliver better care.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center mt-8">
            <Button className="rounded-full px-10 py-5 text-lg bg-primary-foreground text-primary hover:bg-primary-foreground/90 font-semibold">Book a Demo</Button>
            <Button variant="outline" className="rounded-full px-10 py-5 text-lg border-2 border-primary-foreground text-primary-foreground hover:bg-primary-foreground/10 font-semibold">Register as a Provider</Button>
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}
