import { useSEO } from "@/hooks/useSEO";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Monitor, Brain, TrendingUp, Star, ArrowRight } from "lucide-react";
import providerPortalImg from "@/assets/provider-portal-dashboard.jpg";
import { SiteLayout } from "@/components/SiteLayout";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { BrochureLeadCapture } from "@/components/BrochureLeadCapture";

const fadeUp = { initial: { opacity: 0, y: 40 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { duration: 0.6 } };

const valueProps = [
  { icon: Monitor, title: "Remote patient monitoring that actually works", body: "Your patients are already using health apps. The problem is those apps don't give you access. With Agatsa One, patients can share their entire health timeline with you — all readings, AI analysis, trend charts — with a single tap. Review before an appointment, not during it." },
  { icon: Brain, title: "AI pre-analysis so you see the signal, not the noise", body: "Nera AI processes every patient reading before you see it. By the time a reading lands in your provider portal, it's already been classified — normal, borderline, abnormal, or critical. You focus on what matters. Nera handles the volume." },
  { icon: TrendingUp, title: "A smarter way to practice medicine", body: "Your patients are already generating health data. Agatsa One makes it visible to you. See trends across your entire patient panel. Spot who needs attention before they call your receptionist. Spend your consultation time on decisions — not on collecting baseline data you should have had a week ago." },
];

const steps = [
  { n: "1", title: "Register your clinic", copy: "Register your clinic on the Agatsa One Provider Portal — takes 10 minutes, free to join. Verification is completed within 24 hours." },
  { n: "2", title: "Invite your patients", copy: "Invite your patients to download Agatsa One and connect their devices. They approve sharing with your practice. You're connected instantly." },
  { n: "3", title: "Access your dashboard", copy: "Access your provider dashboard — patient list, reading summaries, alerts, AI analysis. Flag patients for follow-up. Review ECGs before appointments." },
  { n: "4", title: "Deliver better care between visits", copy: "Catch deterioration before it becomes an emergency. Reduce unnecessary appointments. Your patients feel supported between visits — and you see the full picture when they arrive." },
];

const faqs = [
  { q: "Is patient data shared with me automatically?", a: "No. Patients must explicitly approve sharing with your practice. They can also revoke access at any time. We take data privacy seriously — patients are always in control of who sees their health data." },
  { q: "Do I need to prescribe specific Agatsa One devices to my patients?", a: "No — though we do recommend specific devices based on condition. Patients can use any compatible Agatsa One device, and all readings appear in your provider portal regardless of which device they use." },
  { q: "Is the ECG data medico-legally valid?", a: "SanketLife ECG is a CDSCO Class B certified medical device. Its readings carry the same legal standing as any other certified medical device. The ECG PDF generated by Agatsa One includes timestamps, device ID, CDSCO certification number, and Nera AI analysis notes." },
  { q: "Can I enrol my patients in Care Programmes?", a: "Yes. As a provider, you can recommend specific Care Programmes for your patients. For premium oversight (where you receive weekly programme reports), this is available on our Provider Growth and Pro plans." },
];

const providerPlans = [
  {
    name: "Starter",
    tagline: "For individual doctors",
    price: "₹199",
    priceColor: "text-[#7C4DFF]",
    capacity: "Up to 10 patients",
    capacityStyle: "bg-gray-100 text-gray-600",
    highlighted: false,
    features: [
      { included: true, text: "Free to register — no card needed" },
      { included: true, text: "Patient vitals dashboard" },
      { included: true, text: "ECG review before appointments" },
      { included: true, text: "Nera AI risk score per patient" },
      { included: true, text: "Alert notifications (in-app)" },
      { included: true, text: "Patient data shared with consent" },
      { included: false, text: "Care Programme oversight" },
      { included: false, text: "Bulk patient import" },
      { included: false, text: "API access" },
    ],
    cta: "Register Free",
    ctaStyle: "border-2 border-[#7C4DFF] text-[#7C4DFF] hover:bg-purple-50 bg-transparent",
    href: "mailto:info@agatsa.com?subject=Provider Registration - Starter",
  },
  {
    name: "Growth",
    tagline: "For busy clinics",
    price: "₹249",
    priceColor: "text-[#7C4DFF]",
    capacity: "Up to 50 patients",
    capacityStyle: "bg-purple-100 text-purple-700",
    highlighted: true,
    badge: "⭐ Most Popular",
    features: [
      { included: true, text: "Everything in Starter, plus:" },
      { included: true, text: "All 5 Care Programme oversight" },
      { included: true, text: "Weekly programme progress reports" },
      { included: true, text: "Patient enrolment via QR code" },
      { included: true, text: "Multi-doctor / nurse access" },
      { included: true, text: "Camp screening module" },
      { included: true, text: "Priority email support" },
      { included: false, text: "API access" },
      { included: false, text: "White-label options" },
    ],
    cta: "Get Started",
    ctaStyle: "bg-[#7C4DFF] text-white shadow-lg shadow-purple-200 hover:bg-purple-700",
    href: "mailto:info@agatsa.com?subject=Provider Registration - Growth",
  },
  {
    name: "Pro",
    tagline: "For multi-doctor practices",
    price: "₹299",
    priceColor: "text-[#1A1A2E]",
    capacity: "Up to 200 patients",
    capacityStyle: "bg-gray-100 text-gray-600",
    highlighted: false,
    features: [
      { included: true, text: "Everything in Growth, plus:" },
      { included: true, text: "REST API access for EMR integration" },
      { included: true, text: "Aggregate population health analytics" },
      { included: true, text: "Bulk patient import (CSV)" },
      { included: true, text: "Custom alert thresholds per patient" },
      { included: true, text: "Dedicated onboarding support" },
      { included: true, text: "SLA-backed response time (24h)" },
    ],
    cta: "Contact Us",
    ctaStyle: "border-2 border-gray-200 text-gray-700 hover:border-purple-400 hover:text-purple-700 bg-transparent",
    href: "mailto:info@agatsa.com?subject=Provider Registration - Pro",
  },
  {
    name: "Enterprise",
    tagline: "For hospitals & health systems",
    price: "₹349",
    priceColor: "text-[#1A1A2E]",
    capacity: "Unlimited patients",
    capacityStyle: "bg-green-100 text-green-700",
    highlighted: false,
    features: [
      { included: true, text: "Everything in Pro, plus:" },
      { included: true, text: "Unlimited patient capacity" },
      { included: true, text: "Multi-location / multi-department setup" },
      { included: true, text: "White-label patient app (your brand)" },
      { included: true, text: "HL7 FHIR-ready API for HIS/EMR" },
      { included: true, text: "Dedicated implementation team" },
      { included: true, text: "Custom SLA and uptime guarantee" },
      { included: true, text: "Quarterly business review" },
    ],
    cta: "Talk to Sales",
    ctaStyle: "bg-[#1A1A2E] text-white hover:bg-gray-800",
    href: "mailto:info@agatsa.com?subject=Enterprise Provider Inquiry",
  },
];

export default function ForDoctorsPage() {
  useSEO({ title: "Remote Patient Monitoring for Doctors — Agatsa One Provider Platform", description: "Monitor your patients between appointments. Review ECGs, metabolic trends, and BP data in your provider portal. Free to join. Start in 10 minutes." });

  return (
    <SiteLayout>
      {/* Hero */}
      <section className="pt-8 pb-8 bg-gradient-to-b from-background to-[hsl(260,100%,97%)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12 items-center">
          <motion.div {...fadeUp}>
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">For Doctors & Clinics</p>
            <h1 className="text-3xl md:text-5xl font-extrabold text-foreground leading-tight">
              You don't have time to track every patient.
              <br className="hidden md:block" /> <span className="text-primary">Nera AI</span> does it for you.
            </h1>
            <p className="text-base text-muted-foreground mt-4 max-w-[540px]">
              Nera AI gives you the data you've always wanted but never had — <span className="text-foreground font-semibold">without adding a single minute to your workflow.</span>
            </p>
            <ul className="mt-5 space-y-2.5 max-w-[540px]">
              {[
                { icon: "📋", text: "Patient's ECG from last Thursday" },
                { icon: "📈", text: "Metabolic trends over the past 30 days" },
                { icon: "💓", text: "BP readings at 2 AM" },
                { icon: "😴", text: "Sleep quality the night before a complaint" },
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2.5 text-sm text-muted-foreground">
                  <span className="text-base shrink-0">{item.icon}</span>
                  <span><span className="text-foreground font-medium">{item.text}</span> — available before they walk in</span>
                </li>
              ))}
            </ul>
            <p className="text-xs text-muted-foreground/70 mt-4 italic max-w-[540px]">
              Trained on real patient data from Agatsa's devices — not simulated or limited datasets.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 mt-8">
              <a href="mailto:info@agatsa.com?subject=Provider Demo Request">
                <Button className="rounded-full px-8 py-4 text-base w-full">Book a Demo</Button>
              </a>
              <BrochureLeadCapture
                brochureType="doctors"
                brochurePath="/agatsa-one-doctors-brochure.pdf"
                buttonText="Download Provider Guide"
              >
                <Button variant="outline" className="rounded-full px-8 py-4 text-base border-2 border-primary text-primary w-full">Download Provider Guide</Button>
              </BrochureLeadCapture>
            </div>
          </motion.div>
          <motion.img {...fadeUp} transition={{ duration: 0.6, delay: 0.15 }} src={providerPortalImg} alt="Agatsa One Provider Portal Dashboard" className="w-full rounded-3xl shadow-2xl" />
        </div>
      </section>

      {/* Value Props */}
      <section className="py-20 bg-background">
        <div className="max-w-5xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Why Agatsa One</p>
            <h2 className="text-3xl font-bold text-foreground">What changes when your patients use Agatsa One</h2>
          </motion.div>
          <div className="grid md:grid-cols-3 gap-6">
            {valueProps.map((v, i) => (
              <motion.div key={v.title} {...fadeUp} transition={{ duration: 0.5, delay: i * 0.1 }} className="bg-card border border-border rounded-2xl p-6">
                <v.icon className="h-8 w-8 text-primary mb-4" />
                <h3 className="text-base font-bold text-foreground">{v.title}</h3>
                <p className="text-sm text-muted-foreground mt-2">{v.body}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-20 bg-[hsl(260,100%,97%)]">
        <div className="max-w-5xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">Getting Started</p>
            <h2 className="text-3xl font-bold text-foreground">From sign-up to active monitoring in one day.</h2>
          </motion.div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((s, i) => (
              <motion.div key={s.n} {...fadeUp} transition={{ duration: 0.5, delay: i * 0.1 }} className="text-center lg:text-left">
                <div className="w-10 h-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-lg font-bold mx-auto lg:mx-0">{s.n}</div>
                <h3 className="text-lg font-bold text-foreground mt-4">{s.title}</h3>
                <p className="text-sm text-muted-foreground mt-2">{s.copy}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonial */}
      <section className="py-20 bg-background">
        <motion.div {...fadeUp} className="max-w-[800px] mx-auto px-4">
          <div className="bg-[hsl(260,100%,97%)] rounded-3xl p-8 md:p-12">
            <div className="flex gap-0.5 mb-4">
              {[...Array(5)].map((_, i) => <Star key={i} className="h-5 w-5 fill-yellow-400 text-yellow-400" />)}
            </div>
            <blockquote className="text-lg md:text-xl italic text-foreground leading-relaxed">
              "I started recommending Agatsa One to my high-risk cardiac patients 8 months ago. Today, I have 47 patients actively monitoring with the app. I check the portal dashboard every morning — takes 5 minutes. I've caught three significant arrhythmias between scheduled appointments. One of those patients would likely have ended up in the ICU. This platform has genuinely changed how I practice."
            </blockquote>
            <div className="flex items-center gap-3 mt-6">
              <img src="https://placehold.co/64x64/7C4DFF/FFFFFF?text=AK" alt="Dr. Arun Krishnamurthy" className="w-12 h-12 rounded-full" />
              <div>
                <p className="font-bold text-foreground">Dr. Arun Krishnamurthy</p>
                <p className="text-sm text-muted-foreground">Cardiologist, Apollo Hospitals, Bengaluru</p>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Provider Pricing */}
      <section className="py-20 bg-[hsl(260,100%,97%)]">
        <div className="max-w-6xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#7C4DFF] mb-3">PROVIDER PRICING</p>
            <h2 className="text-3xl md:text-[40px] font-extrabold text-[#1A1A2E] leading-tight">
              Free to register.<br />Pay only for patients you actively monitor.
            </h2>
            <p className="text-lg text-[#4A4A68] mt-3 max-w-xl mx-auto">
              No monthly subscription. No setup fee. No lock-in. You only pay for patients who are actively enrolled in monitoring — and only while they're active.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mt-12">
            {providerPlans.map((plan, i) => (
              <motion.div
                key={plan.name}
                {...fadeUp}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className={`rounded-3xl p-8 bg-white flex flex-col relative ${
                  plan.highlighted
                    ? "border-2 border-[#7C4DFF] shadow-2xl shadow-purple-100 z-10"
                    : "border border-gray-200 shadow-sm"
                }`}
              >
                {plan.badge && (
                  <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-[#7C4DFF] text-white text-xs font-bold px-4 py-1.5 rounded-full shadow whitespace-nowrap">
                    {plan.badge}
                  </span>
                )}
                <h3 className={`text-xl font-bold ${plan.highlighted ? "text-[#7C4DFF]" : "text-[#1A1A2E]"}`}>{plan.name}</h3>
                <p className="text-sm text-[#4A4A68] mt-1">{plan.tagline}</p>
                <div className="mt-6">
                  <span className={`text-5xl font-extrabold ${plan.priceColor}`}>{plan.price}</span>
                  <span className="text-[15px] text-[#4A4A68]">/patient/month</span>
                </div>
                <span className={`inline-block mt-3 ${plan.capacityStyle} rounded-full px-3 py-1 text-sm font-medium w-fit`}>
                  {plan.capacity}
                </span>
                <div className="border-t border-gray-100 my-6" />
                <p className="text-[13px] font-semibold uppercase tracking-wider text-gray-400 mb-3">WHAT'S INCLUDED</p>
                <ul className="space-y-3 text-sm text-[#4A4A68] flex-1">
                  {plan.features.map((f, fi) => (
                    <li key={fi} className="flex items-start gap-2">
                      <span className="shrink-0 mt-0.5">{f.included ? "✅" : "❌"}</span>
                      <span>{f.text}</span>
                    </li>
                  ))}
                </ul>
                <div className="mt-8">
                  <a href={plan.href} className="block">
                    <button className={`w-full rounded-full py-3.5 font-semibold text-base transition-colors ${plan.ctaStyle}`}>
                      {plan.cta}
                    </button>
                  </a>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Explainer Note */}
          <motion.div {...fadeUp} className="mt-10 max-w-3xl mx-auto">
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 text-center">
              <p className="text-[15px] text-[#4A4A68]">
                💡 <strong>How billing works:</strong> You register free. When you enrol a patient in active monitoring, they count toward your plan. A patient is 'active' only while they have an ongoing monitoring relationship with your practice. Remove a patient and billing stops. No hidden fees.
              </p>
              <a
                href="mailto:info@agatsa.com?subject=Provider Pricing Question"
                className="inline-block mt-3 text-[#7C4DFF] font-semibold underline underline-offset-2 text-sm"
              >
                Questions? Email us at info@agatsa.com →
              </a>
            </div>
          </motion.div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 bg-background">
        <div className="max-w-3xl mx-auto px-4">
          <motion.div {...fadeUp} className="text-center mb-8">
            <p className="text-xs font-semibold uppercase tracking-widest text-primary mb-3">FAQ</p>
            <h2 className="text-2xl font-bold text-foreground">Common questions from doctors</h2>
          </motion.div>
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((f, i) => (
              <AccordionItem key={i} value={`faq-${i}`}>
                <AccordionTrigger className="text-left text-foreground">{f.q}</AccordionTrigger>
                <AccordionContent className="text-muted-foreground">{f.a}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Final CTA */}
      <section className="bg-primary py-20">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-primary-foreground">Ready to monitor your patients beyond the waiting room?</h2>
          <p className="text-primary-foreground/80 mt-3 text-lg">Join doctors and clinics across India using Agatsa One to deliver better care.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center mt-8">
            <a href="mailto:info@agatsa.com?subject=Provider Demo Request">
              <Button className="rounded-full px-10 py-5 text-lg bg-primary-foreground text-primary hover:bg-primary-foreground/90 font-semibold">Book a Demo</Button>
            </a>
            <a href="mailto:info@agatsa.com?subject=Register as Provider">
              <Button variant="outline" className="rounded-full px-10 py-5 text-lg border-2 border-primary-foreground text-primary-foreground hover:bg-primary-foreground/10 font-semibold">Register as a Provider</Button>
            </a>
          </div>
        </div>
      </section>
    </SiteLayout>
  );
}
